[tool.uv]
package = false

[project]
name = "autotomeqc-instrument"
version = "0.1.0"
description = "AutoTome monorepo workspace"
requires-python = ">=3.11"
dependencies = [
    "autotomeqc[api]",
    "autotome-ui"
]

[tool.uv.sources]
autotomeqc = { workspace = true }
autotome-ui = { workspace = true }

[tool.uv.workspace]
members = [
    "qc",
    "web"
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "ruff>=0.9.9",
    "mypy>=1.19.1",
    "pytest-asyncio>=1.3.0",
]

[tool.pytest.ini_options]
pythonpath = ["qc/src", "web/src"]
asyncio_mode = "auto"
addopts = "-p nicegui.testing.plugin"
main_file = "web/src/autotome_ui/main.py"

[tool.mypy]
mypy_path = ["qc/src", "web/src"]
namespace_packages = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = "imagesize"
ignore_missing_imports = true