qc:
  fps: 1
  output_dir: "example/output"
  save_segmented_images: true
  yolo:
    weights_path: "weights/seg_fast.pt" 
    conf_thresh: 0.7
    iou_thresh: 0.45
    img_size: 960
    img_dim: [960, 960]
    max_det: 30
    loop_bbox_margin: 30
  section_coverage:
    weights_path: "weights/setction_coverage_v1.pt"
    img_size: 224
    img_dim: [224, 224]
    pass_labels: ["full_section"]
    min_confidence: 0.5
  knife_mark:
    weights_path: "weights/knife_mark_v1.pt"
    img_size: 640
    img_dim: [640, 640]
    pass_labels: ["knifemark_none"]
    min_confidence: 0.5
  thickness_consistency:
    weights_path: "weights/thickness_consistency_v1.pt"
    img_size: 224
    img_dim: [224, 224]
    pass_labels: ["Consistent"]
    min_confidence: 0.5
  thickness:
    weights_path: "weights/thickness_v1.pt"
    img_size: 224
    img_dim: [224, 224]
    pass_labels: ["ANY"]
    min_confidence: 0.1