name: CI/CD Pipeline
run-name: CI/CD Pipeline - ${{ github.run_number }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - dev

jobs:
  # 1. Run Linter and Tests first
  lint-and-test:
    uses: ./.github/workflows/test_lint_type.yml

  # 2. Run the Tagging logic ONLY if the tests pass
  tag-and-release:
    needs: lint-and-test
    uses: AllenNeuralDynamics/.github/.github/workflows/tag.yml@main
    secrets: inherit
    with:
      runner_label: 'ubuntu-latest'
      # custom_release_rules: 'fix:patch,feat:minor,breaking:major'
