name: CI/CD Pipeline
run-name: CI/CD Pipeline - ${{ github.run_number }} on ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - dev
      - feat-docs

jobs:
  # 1. Run Linter and Tests first
  pytest:
    uses: AllenNeuralDynamics/.github/.github/workflows/test.yml@main
  lint:
    uses: AllenNeuralDynamics/.github/.github/workflows/lint.yml@main
  type-check:
    uses: ./.github/workflows/type.yml  # TODO: Move this to AllenNeuralDynamics/.github if fixed
  docs:
    uses: ./.github/workflows/docs.yml

  # 2. Run the Tagging logic ONLY if the tests pass
  tag-and-release:
    needs: [pytest, lint, type-check, docs]
    uses: AllenNeuralDynamics/.github/.github/workflows/tag.yml@main
    secrets: inherit
    with:
      runner_label: 'ubuntu-latest'
      # custom_release_rules: 'fix:patch,feat:minor,breaking:major'