on:
  push:
    branches:
      - main
      - dev
      - 'feat-**'

jobs:
  call-tag-workflow:
    uses: AllenNeuralDynamics/.github/.github/workflows/tag.yml@main
    permissions:
      contents: write
    with:
      runner_label: 'ubuntu-latest'