name: Tag Bump

on:
  workflow_call:
    inputs: 
      runner_label: 
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'

jobs:
  tag: 
    runs-on: ${{ inputs.runner_label }}
    permissions:
      contents: write
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          append_to_pre_release_tag: 'dev'
          pre_release_branches: dev,feat-cicd
          # custom_release_rules: 'fix:patch,feat:minor,breaking:major'
      - name: Install UV 
        uses: astral-sh/setup-uv@v5
      - name: Update Version in pyproject.toml
        run: uvx --from=toml-cli toml set --toml-path=pyproject.toml project.version ${{ steps.tag_version.outputs.new_version }}
      - name: Commit and push pyproject.toml version bump
        uses: EndBug/add-and-commit@v9
        with:
          add: 'pyproject.toml'
          default_author: github_actions
          message: "ci: version bump to ${{ steps.tag_version.outputs.new_version }}"
          push: true