name: Tag and Publish
on:
  push:
    branches:
      - main
      - dev
jobs:
  test-lint-and-type-check:
    # uses: AllenNeuralDynamics/aind-python-library-template/.github/workflows/test_lint_type.yml@main
    uses: ./.github/workflows/test_lint_type.yml
    secrets: inherit

  #publish: 
  #  runs-on: self-hosted-good 
  #  needs: tag
  #  env: 
  #    UV_PYTHON_INSTALL_DIR: C:\ProgramData\AIBS_MPE\uv_python
  #    UV_TOOL_DIR: C:\ProgramData\AIBS_MPE\uv_python
  #  steps:
  #    - name: Install UV 
  #      uses: astral-sh/setup-uv@v5
  #    - name: Build Project
  #      run: uv build
  #    - name: Publish Project to eng-tools devpi
  #      run: uv publish --publish-url http://eng-tools:3141/aibs/packages --username aibs --password aibs
